site_name: Product Store API
theme:
  name: material
nav:
  - 'Введение': 'index.md'
  - 'API': 'api_docs.md'
  - 'Архитектура': 'architecture.md'
  - 'Микросервисы': 'microservices.md'
  - 'База данных': 'database.md'
  - 'Мониторинг': 'monitoring.md'
  - 'Нагрузочное тестирование': 'load_testing.md'
  - 'Тестирование': 'testing.md'
  - 'Аутентификация': 'authentication.md'
  - 'Профилирование': 'profiling.md'
  - 'Анализ Ansible': 'ansible_analysis.md'
  - 'Планы на будущее': 'future_plans.md'
  - 'Воспроизведение алертов': 'reproduce_alerts.md'

extra_javascript:
  - https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js
  - https://unpkg.com/swagger-ui-dist@3/swagger-ui-standalone-preset.js
  
extra_css:
  - https://unpkg.com/swagger-ui-dist@3/swagger-ui.css 