---
# Путь на целевом сервере, куда будет скопирован проект
project_dest_path: "/opt/microservices-app"

# Список кастомных Docker-образов, которые нужно собрать
services_to_build:
  - { name: "backend", path: "{{ project_dest_path }}/app/backend" }
  - { name: "cart-service", path: "{{ project_dest_path }}/app/cart-service" }
  - { name: "order-service", path: "{{ project_dest_path }}/app/order-service" }
  - { name: "user-service", path: "{{ project_dest_path }}/app/user-service" }
  - { name: "nginx", path: "{{ project_dest_path }}/app/nginx" }
  - { name: "alertmanager", path: "{{ project_dest_path }}/infra/alertmanager" }
  - { name: "cassandra", path: "{{ project_dest_path }}/infra/cassandra" }
  - { name: "locust", path: "{{ project_dest_path }}/infra/locust.Dockerfile" } # Указываем путь к Dockerfile