services:
  nginx:
    build:
      context: ..
      dockerfile: app/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - product-store-net
    depends_on:
      - backend
      - docs

  backend:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    environment:
      - CASSANDRA_HOST=cassandra
    volumes:
      # Пути в volumes относительны YAML-файла, поэтому ../ выходит в корень
      - ../app/backend/src:/app/src
    networks:
      - product-store-net
    depends_on:
      cassandra:
        condition: service_healthy

  docs:
    build:
      context: ..
      dockerfile: app/docs/Dockerfile
    networks:
      - product-store-net

  cassandra:
    image: cassandra:4.1
    networks:
      - product-store-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra-data:
    driver: local

networks:
  product-store-net:
    driver: bridge