services:
  nginx:
    build:
      context: ..
      dockerfile: app/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - product-store-net
    depends_on:
      - backend
      - docs
      - cart-service
      - order-service
      - user-service

  backend:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    environment:
      - CASSANDRA_HOST=cassandra
    volumes:
      # Пути в volumes относительны YAML-файла, поэтому ../ выходит в корень
      - ../app/backend/src:/app/src
    networks:
      - product-store-net
    depends_on:
      cassandra:
        condition: service_healthy

  cart-service:
    build:
      context: ..
      dockerfile: app/cart-service/Dockerfile
    environment:
      - BACKEND_HOST=backend
      - ORDER_SERVICE_HOST=order-service
    volumes:
      - ../app/cart-service/src:/app/src
    networks:
      - product-store-net
    depends_on:
      - backend

  order-service:
    build:
      context: ..
      dockerfile: app/order-service/Dockerfile
    environment:
      - BACKEND_HOST=backend
    volumes:
      - ../app/order-service/src:/app/src
    networks:
      - product-store-net
    depends_on:
      - backend

  user-service:
    build:
      context: ..
      dockerfile: app/user-service/Dockerfile
    environment:
      - CART_SERVICE_HOST=cart-service
      - ORDER_SERVICE_HOST=order-service
    volumes:
      - ../app/user-service/src:/app/src
    networks:
      - product-store-net
    depends_on:
      - cart-service
      - order-service

  docs:
    build:
      context: ..
      dockerfile: app/docs/Dockerfile
    networks:
      - product-store-net

  cassandra:
    image: cassandra:4.1
    networks:
      - product-store-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra-data:
    driver: local

networks:
  product-store-net:
    driver: bridge