---
- name: Pre-deployment checks
  include_tasks: pre_checks.yml

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
  become: yes

- name: Create app directory
  ansible.builtin.file:
    path: /opt/microservices
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Configure system limits
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 65536
      * hard nofile 65536
      * soft nproc 32768
      * hard nproc 32768
    marker: "# {mark} ANSIBLE MANAGED BLOCK - System limits"
  become: yes

- name: Configure sysctl parameters
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: 'vm.max_map_count', value: '262144' }
    - { name: 'net.core.somaxconn', value: '1024' }
    - { name: 'fs.file-max', value: '2097152' }
  become: yes