groups:
  - name: application_latency_alerts
    rules:
      # ПРАВИЛО 1: P99 Latency для Backend API
      - alert: BackendHighP99Latency
        expr: |
          histogram_quantile(0.99,
            sum by (le, endpoint) (
              # ИСПРАВЛЕНИЕ: Убран некорректный префикс "/api/".
              # Теперь селектор будет правильно находить метрики для эндпоинтов, начинающихся с /products/
              rate(http_request_duration_seconds_bucket{job="backend-api", endpoint=~"/products/.*"}[5m])
            )
          ) > 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Высокая задержка P99 на Backend ({{ $labels.endpoint }})"
          description: "P99 время ответа для эндпоинта {{ $labels.endpoint }} превысило 500ms. Текущее значение: {{ $value | printf \"%.3f\" }}s."

  - name: database_alerts
    rules:
      # ПРАВИЛО 4: RPS (запросы в секунду) для Cassandra
      - alert: CassandraHighRPS
        expr: |
          sum by (cluster) (
            rate(mcac_client_request_latency_total[1m])
          ) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Высокий RPS в кластере Cassandra"
          description: "Общий RPS для кластера Cassandra '{{ $labels.cluster }}' превысил 100. Текущее значение: {{ $value | printf \"%.2f\" }} запросов/сек."