---
# Application deployment settings
app_directory: "/opt/microservices"
local_project_path: "../../../"
deploy_from_git: false
git_repo_url: "https://github.com/user/microservices.git"
git_branch: "main"

# Docker settings
compose_project_name: "microservices"
app_environment: "production"
debug_mode: "false"

# Database configuration
cassandra_hosts: "cassandra:9042"
cassandra_keyspace: "ecommerce"

# Authentication
jwt_secret: "{{ vault_jwt_secret | default('change-this-secret-key') }}"
jwt_expiration: "3600"

# Monitoring
prometheus_url: "http://prometheus:9090"
grafana_admin_password: "{{ vault_grafana_password | default('admin') }}"

# Alerting (required variables)
alertmanager_bot_token: "{{ vault_alertmanager_bot_token }}"
alertmanager_chat_id: "{{ vault_alertmanager_chat_id | default('-1001234567890') }}"

# Service URLs
backend_url: "http://backend:8000"
cart_service_url: "http://cart-service:8001"
order_service_url: "http://order-service:8002"
user_service_url: "http://user-service:8003"


# System limits
max_open_files: 65536
max_processes: 32768
