---
# Application deployment settings
app_directory: "/opt/microservices"
local_project_path: "../../../"
deploy_from_git: false
git_repo_url: "https://github.com/alice3e/o11y"
git_branch: "main"

# Docker settings
compose_project_name: "microservices"
app_environment: "production"
debug_mode: "false"

# Database configuration
cassandra_hosts: "cassandra:9042"
#cassandra_keyspace: "ecommerce"

# Monitoring
prometheus_url: "http://prometheus:9090"
grafana_admin_password: "{{ vault_grafana_password | default('admin') }}"

# Alerting (optional variables for testing)
alertmanager_bot_token: "{{ vault_alertmanager_bot_token | default('test-token') }}"
alertmanager_chat_id: "-1002852417922"

# Service URLs
backend_url: "http://backend:8000"
cart_service_url: "http://cart-service:8001"
order_service_url: "http://order-service:8002"
user_service_url: "http://user-service:8003"


# System limits
max_open_files: 65536
max_processes: 32768
